export const albums = [
  {
    id: 'associativism',
    title: 'Associativismo',
    type: 'Pessoas',
    image: '/images/covers/associativism.jpeg',
    route: '/albums/associativism',
    images: [
      '/images/associativism/0.jpg',
      '/images/associativism/1.jpg',
      '/images/associativism/2.jpg',
      '/images/associativism/3.jpg',
      '/images/associativism/4.jpg',
    ]
  },
  {
    id: 'celebrities',
    title: 'Celebridades',
    type: 'Pessoas',
    image: '/images/covers/celebrities.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'celebrities'
      },
    },
    images: [
      '/images/celebrities/0.jpg',
      '/images/celebrities/1.jpg',
      '/images/celebrities/2.jpg',
      '/images/celebrities/3.jpg',
      '/images/celebrities/4.jpg',
      '/images/celebrities/5.jpg',
      '/images/celebrities/6.jpg',
      '/images/celebrities/7.jpg',
      '/images/celebrities/8.jpg',
      '/images/celebrities/9.jpg',
      '/images/celebrities/10.jpg',
    ]
  },
  {
    id: 'events',
    title: 'Eventos',
    type: 'Pessoas',
    image: '/images/covers/corporative_events.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'events'
      },
    },
    images: [
      '/images/events/0.jpg',
      '/images/events/1.jpg',
      '/images/events/2.jpg',
      '/images/events/3.jpg',
      '/images/events/4.jpg',
      '/images/events/5.jpg',
      '/images/events/6.jpg',
      '/images/events/7.jpg',
      '/images/events/8.jpg',
      '/images/events/9.jpg',
      '/images/events/10.jpg',
      '/images/events/11.jpg',
      '/images/events/12.jpg',
      '/images/events/13.jpg',
      '/images/events/14.jpg',
      '/images/events/15.jpg',
      '/images/events/16.jpg',
      '/images/events/17.jpg',
      '/images/events/18.jpg',
      '/images/events/19.jpg',
      '/images/events/20.jpg',
      '/images/events/21.jpg',
      '/images/events/22.jpg',
      '/images/events/23.jpg',
      '/images/events/24.jpg',
      '/images/events/25.jpg',
      '/images/events/26.jpg',
      '/images/events/27.jpg',
      '/images/events/28.jpg',
      '/images/events/29.jpg',
    ]
  },
  {
    id: 'industrials',
    title: 'Industriais',
    type: 'Indústria',
    image: '/images/covers/industrial.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'industrials'
      },
    },
    images: [
      '/images/events/0.jpg',
      '/images/events/1.jpg',
      '/images/events/2.jpg',
      '/images/events/3.jpg',
      '/images/events/4.jpg',
      '/images/events/5.jpg',
      '/images/events/6.jpg',
      '/images/events/7.jpg',
      '/images/events/8.jpg',
      '/images/events/9.jpg',
      '/images/events/10.jpg',
      '/images/events/11.jpg',
      '/images/events/12.jpg',
      '/images/events/13.jpg',
      '/images/events/14.jpg',
      '/images/events/15.jpg',
      '/images/events/16.jpg',
      '/images/events/17.jpg',
      '/images/events/18.jpg',
      '/images/events/19.jpg',
      '/images/events/20.jpg',
      '/images/events/21.jpg',
      '/images/events/22.jpg',
      '/images/events/23.jpg',
      '/images/events/24.jpg',
      '/images/events/25.jpg',
      '/images/events/26.jpg',
      '/images/events/27.jpg',
      '/images/events/28.jpg',
      '/images/events/29.jpg',
      '/images/events/30.jpg',
      '/images/events/31.jpg',
      '/images/events/32.jpg',
      '/images/events/33.jpg',
      '/images/events/34.jpg',
      '/images/events/35.jpg',
      '/images/events/36.jpg',
      '/images/events/37.jpg',
      '/images/events/38.jpg',
    ]
  },
  {
    id: 'interiors',
    title: 'Interiores',
    type: 'Lugares',
    image: '/images/covers/interiors.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'interiors'
      },
    },
    images: [
      '/images/events/0.jpg',
      '/images/events/1.jpg',
      '/images/events/2.jpg',
      '/images/events/3.jpg',
      '/images/events/4.jpg',
      '/images/events/5.jpg',
      '/images/events/6.jpg',
      '/images/events/7.jpg',
      '/images/events/8.jpg',
      '/images/events/9.jpg',
      '/images/events/10.jpg',
      '/images/events/11.jpg',
      '/images/events/12.jpg',
      '/images/events/13.jpg',
      '/images/events/14.jpg',
      '/images/events/15.jpg',
      '/images/events/16.jpg',
      '/images/events/17.jpg',
      '/images/events/18.jpg',
      '/images/events/19.jpg',
      '/images/events/20.jpg',
      '/images/events/21.jpg',
      '/images/events/22.jpg',
      '/images/events/23.jpg',
      '/images/events/24.jpg',
      '/images/events/25.jpg',
      '/images/events/26.jpg',
      '/images/events/27.jpg',
      '/images/events/28.jpg',
    ]
  },
  {
    id: 'products',
    title: 'Produtos',
    type: 'Indústria',
    image: '/images/covers/products.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'products'
      },
    },
    images: [
      '/images/products/0.jpg',
      '/images/products/1.jpg',
      '/images/products/2.jpg',
      '/images/products/3.jpg',
      '/images/products/4.jpg',
      '/images/products/5.jpg',
      '/images/products/6.jpg',
      '/images/products/7.jpg',
      '/images/products/8.jpg',
      '/images/products/9.jpg',
      '/images/products/10.jpg',
      '/images/products/11.jpg',
      '/images/products/12.jpg',
      '/images/products/13.jpg',
      '/images/products/14jpg',
      '/images/products/15.jpg',
      '/images/products/16.jpg',
      '/images/products/17.jpg',
      '/images/products/18.jpg',
      '/images/products/19.jpg',
      '/images/products/20.jpg',
      '/images/products/21.jpg',
      '/images/products/22.jpg',
      '/images/products/23.jpg',
      '/images/products/24.jpg',
      '/images/products/25.jpg',
      '/images/products/26.jpg',
      '/images/products/27.jpg',
      '/images/products/28.jpg',
      '/images/products/29.jpg',
    ]
  },
  {
    id: 'professionals',
    title: 'Profissionais',
    type: 'Pessoas',
    image: 'images/covers/professionals.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'professionals'
      },
    },
    images: [
      '/images/products/0.jpg',
      '/images/products/1.jpg',
      '/images/products/2.jpg',
      '/images/products/3.jpg',
      '/images/products/4.jpg',
      '/images/products/5.jpg',
      '/images/products/6.jpg',
      '/images/products/7.jpg',
      '/images/products/8.jpg',
      '/images/products/9.jpg',
      '/images/products/10.jpg',
      '/images/products/11.jpg',
      '/images/products/12.jpg',
      '/images/products/13.jpg',
      '/images/products/14jpg',
      '/images/products/15.jpg',
      '/images/products/16.jpg',
      '/images/products/17.jpg',
      '/images/products/18.jpg',
      '/images/products/19.jpg',
      '/images/products/20.jpg',
      '/images/products/21.jpg',
      '/images/products/22.jpg',
    ]
  },
]

export const specialties = [
  {
    title: 'Associativismo',
    subtitle:
      'A importância do associativismo em defesa de determinado segmento de mercado e do desenvolvimento econômico e social pode ser mostrada através de reportagem fotográfica. As imagens destacam o trabalho desenvolvimento pelas entidades da iniciativa privada, como federações, associações empresariais, sindicatos patronais e fundações, através de suas ações, eventos e estrutura de atendimento aos associados.',
    image: 'images/covers/associativism.jpeg',
  },
  {
    title: 'Celebridades',
    subtitle:
      'A fotografia de celebridades captura a essência das pessoas em momentos de relevância. Possui importância especial em inaugurações, feiras, convenções, workshops, palestras, visitas, lançamentos, coletivas de imprensa e confraternizações.',
    image: 'images/covers/celebrities.jpeg',
  },
  {
    title: 'Eventos corporativos',
    subtitle:
      'A exposição dos eventos corporativos é essencial para decretar o seu sucesso. A cobertura fotográfica é, portanto, imprescindível para divulgar a realização de feiras, lançamentos, palestras, inaugurações, confraternizações e uma infinidade de eventos que valorizem a imagem da empresa. O acompanhamento dos eventos permite capturar imagens de interação da empresa com seus clientes, divulgando de forma instantânea e completa todo o seu potencial.',
    image: 'images/covers/corporative_events.jpeg',
  },
  {
    title: 'Indústriais',
    subtitle:
      'A fotografia industrial consegue mostrar uma fábrica em ação, revelando a perfeita sinergia entre profissionais, processo e equipamentos. Dos pequenos detalhes às amplas imagens produtivas, são destacadas as características que movem a empresa, sua infraestrutura, sua tecnologia e a qualificação de seus profissionais.',
    image: 'images/covers/industrial.jpeg',
  },
  {
    title: 'Interiores',
    subtitle:
      'A fotografia registra a beleza dos ambientes através dos traços da arquitetura, da decoração e da iluminação. Para uma composição de qualidade, é necessário enquadramento adequado, bom gosto e técnicas apuradas de captação de cor, textura, perspectiva, detalhes e luz.',
    image: 'images/covers/interiors.jpeg',
  },
  {
    title: 'Produtos',
    subtitle:
      'A técnica da fotografia Still extrai todos os detalhes de produtos, destacando suas formas, texturas e qualidade de acabamento. O profissionalismo envolvido em todo o processo de captura da imagem e pós-produção garante imagens que agregam valor ao produto. A Metzger Fotografia realiza o trabalho em seu próprio estúdio ou na empresa através de equipamentos móveis.',
    image: 'images/covers/products.jpeg',
  },
  {
    title: 'Profissionais',
    subtitle:
      'A fotografia executiva ajuda a dar uma imagem humanizada à empresa. Ela releva o engajamento das pessoas que formam uma empresa, mostra o trabalho integrado de equipes e destaca o atendimento diferenciado que ela pode oferecer ao mercado.',
    image: 'images/covers/professionals.jpeg',
  },
]