export const albums = [
  {
    id: 'associativism',
    title: 'Associativismo',
    type: 'Pessoas',
    image: '/images/covers/associativism.jpeg',
    route: '/albums/associativism',
    images: [
      '/images/associativism/0.jpg',
      '/images/associativism/1.jpg',
      '/images/associativism/2.jpg',
      '/images/associativism/3.jpg',
      '/images/associativism/4.jpg',
    ]
  },
  {
    id: 'celebrities',
    title: 'Celebridades',
    type: 'Pessoas',
    image: '/images/covers/celebrities.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'celebrities'
      },
    },
    images: [
      '/images/celebrities/0.jpg',
      '/images/celebrities/1.jpg',
      '/images/celebrities/2.jpg',
      '/images/celebrities/3.jpg',
      '/images/celebrities/4.jpg',
      '/images/celebrities/5.jpg',
      '/images/celebrities/6.jpg',
      '/images/celebrities/7.jpg',
      '/images/celebrities/8.jpg',
      '/images/celebrities/9.jpg',
      '/images/celebrities/10.jpg',
    ]
  },
  {
    id: 'events',
    title: 'Eventos',
    type: 'Pessoas',
    image: '/images/covers/corporative_events.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'events'
      },
    },
    images: [
      '/images/events/0.jpg',
      '/images/events/1.jpg',
      '/images/events/2.jpg',
      '/images/events/3.jpg',
      '/images/events/4.jpg',
      '/images/events/5.jpg',
      '/images/events/6.jpg',
      '/images/events/7.jpg',
      '/images/events/8.jpg',
      '/images/events/9.jpg',
      '/images/events/10.jpg',
      '/images/events/11.jpg',
      '/images/events/12.jpg',
      '/images/events/13.jpg',
      '/images/events/14.jpg',
      '/images/events/15.jpg',
      '/images/events/16.jpg',
      '/images/events/17.jpg',
      '/images/events/18.jpg',
      '/images/events/19.jpg',
      '/images/events/20.jpg',
      '/images/events/21.jpg',
      '/images/events/22.jpg',
      '/images/events/23.jpg',
      '/images/events/24.jpg',
      '/images/events/25.jpg',
      '/images/events/26.jpg',
      '/images/events/27.jpg',
      '/images/events/28.jpg',
      '/images/events/29.jpg',
    ]
  },
  {
    id: 'industrials',
    title: 'Industriais',
    type: 'Indústria',
    image: '/images/covers/industrial.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'industrials'
      },
    },
    images: [
      '/images/industrial/0.jpg',
      '/images/industrial/1.jpg',
      '/images/industrial/2.jpg',
      '/images/industrial/3.jpg',
      '/images/industrial/4.jpg',
      '/images/industrial/5.jpg',
      '/images/industrial/6.jpg',
      '/images/industrial/7.jpg',
      '/images/industrial/8.jpg',
      '/images/industrial/9.jpg',
      '/images/industrial/10.jpg',
      '/images/industrial/11.jpg',
      '/images/industrial/12.jpg',
      '/images/industrial/13.jpg',
      '/images/industrial/14.jpg',
      '/images/industrial/15.jpg',
      '/images/industrial/16.jpg',
      '/images/industrial/17.jpg',
      '/images/industrial/18.jpg',
      '/images/industrial/19.jpg',
      '/images/industrial/20.jpg',
      '/images/industrial/21.jpg',
      '/images/industrial/22.jpg',
      '/images/industrial/23.jpg',
      '/images/industrial/24.jpg',
      '/images/industrial/25.jpg',
      '/images/industrial/26.jpg',
      '/images/industrial/27.jpg',
      '/images/industrial/28.jpg',
      '/images/industrial/29.jpg',
      '/images/industrial/30.jpg',
      '/images/industrial/31.jpg',
      '/images/industrial/32.jpg',
      '/images/industrial/33.jpg',
      '/images/industrial/34.jpg',
      '/images/industrial/35.jpg',
      '/images/industrial/36.jpg',
      '/images/industrial/37.jpg',
      '/images/industrial/38.jpg',
    ]
  },
  {
    id: 'interiors',
    title: 'Interiores',
    type: 'Lugares',
    image: '/images/covers/interiors.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'interiors'
      },
    },
    images: [
      '/images/interiors/0.jpg',
      '/images/interiors/1.jpg',
      '/images/interiors/2.jpg',
      '/images/interiors/3.jpg',
      '/images/interiors/4.jpg',
      '/images/interiors/5.jpg',
      '/images/interiors/6.jpg',
      '/images/interiors/7.jpg',
      '/images/interiors/8.jpg',
      '/images/interiors/9.jpg',
      '/images/interiors/10.jpg',
      '/images/interiors/11.jpg',
      '/images/interiors/12.jpg',
      '/images/interiors/13.jpg',
      '/images/interiors/14.jpg',
      '/images/interiors/15.jpg',
      '/images/interiors/16.jpg',
      '/images/interiors/17.jpg',
      '/images/interiors/18.jpg',
      '/images/interiors/19.jpg',
      '/images/interiors/20.jpg',
      '/images/interiors/21.jpg',
      '/images/interiors/22.jpg',
      '/images/interiors/23.jpg',
      '/images/interiors/24.jpg',
      '/images/interiors/25.jpg',
      '/images/interiors/26.jpg',
      '/images/interiors/27.jpg',
      '/images/interiors/28.jpg',
    ]
  },
  {
    id: 'products',
    title: 'Produtos',
    type: 'Indústria',
    image: '/images/covers/products.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'products'
      },
    },
    images: [
      '/images/products/0.jpg',
      '/images/products/1.jpg',
      '/images/products/2.jpg',
      '/images/products/3.jpg',
      '/images/products/4.jpg',
      '/images/products/5.jpg',
      '/images/products/6.jpg',
      '/images/products/7.jpg',
      '/images/products/8.jpg',
      '/images/products/9.jpg',
      '/images/products/10.jpg',
      '/images/products/11.jpg',
      '/images/products/12.jpg',
      '/images/products/13.jpg',
      '/images/products/15.jpg',
      '/images/products/16.jpg',
      '/images/products/17.jpg',
      '/images/products/18.jpg',
      '/images/products/19.jpg',
      '/images/products/20.jpg',
      '/images/products/21.jpg',
      '/images/products/22.jpg',
      '/images/products/23.jpg',
      '/images/products/24.jpg',
      '/images/products/25.jpg',
      '/images/products/26.jpg',
      '/images/products/27.jpg',
      '/images/products/28.jpg',
      '/images/products/29.jpg',
      '/images/products/30.jpg',
      '/images/products/31.jpg',
      '/images/products/32.jpg',
      '/images/products/33.jpg',
      '/images/products/34.jpg',
      '/images/products/35.jpg',
      '/images/products/36.jpg',
      '/images/products/37.jpg',
      '/images/products/38.jpg',
      '/images/products/39.jpg',
      '/images/products/40.jpg',
      '/images/products/41.jpg',
      '/images/products/42.jpg',
      '/images/products/43.jpg',
      '/images/products/45.jpg',
      '/images/products/46.jpg',
      '/images/products/47.jpg',
      '/images/products/48.jpg',
      '/images/products/49.jpg',
      '/images/products/50.jpg',
      '/images/products/51.jpg',
      '/images/products/52.jpg',
      '/images/products/53.jpg',
      '/images/products/54.jpg',
      '/images/products/55.jpg',
      '/images/products/56.jpg',
      '/images/products/57.jpg',
      '/images/products/58.jpg',
      '/images/products/59.jpg',
      '/images/products/60.jpg',
      '/images/products/61.jpg',
      '/images/products/62.jpg',
      '/images/products/63.jpg',
      '/images/products/64.jpg',
      '/images/products/65.jpg',
      '/images/products/66.jpg',
      '/images/products/67.jpg',
      '/images/products/68.jpg',
      '/images/products/69.jpg',
      '/images/products/70.jpg',
      '/images/products/71.jpg',
      '/images/products/72.jpg',
      '/images/products/73.jpg',
    ]
  },
  {
    id: 'professionals',
    title: 'Profissionais',
    type: 'Pessoas',
    image: 'images/covers/professionals.jpeg',
    route: {
      name: 'albums-id',
      params: {
        id: 'professionals'
      },
    },
    images: [
      '/images/professionals/0.jpg',
      '/images/professionals/1.jpg',
      '/images/professionals/2.jpg',
      '/images/professionals/3.jpg',
      '/images/professionals/4.jpg',
      '/images/professionals/5.jpg',
      '/images/professionals/6.jpg',
      '/images/professionals/7.jpg',
      '/images/professionals/8.jpg',
      '/images/professionals/9.jpg',
      '/images/professionals/10.jpg',
      '/images/professionals/11.jpg',
      '/images/professionals/12.jpg',
      '/images/professionals/13.jpg',
      '/images/professionals/14jpg',
      '/images/professionals/15.jpg',
      '/images/professionals/16.jpg',
      '/images/professionals/17.jpg',
      '/images/professionals/18.jpg',
      '/images/professionals/19.jpg',
      '/images/professionals/20.jpg',
      '/images/professionals/21.jpg',
      '/images/professionals/22.jpg',
    ]
  },
]

export const specialties = [
  {
    title: 'Associativismo',
    subtitle:
      'A importância do associativismo em defesa de determinado segmento de mercado e do desenvolvimento econômico e social pode ser mostrada através de reportagem fotográfica. As imagens destacam o trabalho desenvolvimento pelas entidades da iniciativa privada, como federações, associações empresariais, sindicatos patronais e fundações, através de suas ações, eventos e estrutura de atendimento aos associados.',
    image: 'images/covers/associativism.jpeg',
  },
  {
    title: 'Celebridades',
    subtitle:
      'A fotografia de celebridades captura a essência das pessoas em momentos de relevância. Possui importância especial em inaugurações, feiras, convenções, workshops, palestras, visitas, lançamentos, coletivas de imprensa e confraternizações.',
    image: 'images/covers/celebrities.jpeg',
  },
  {
    title: 'Eventos corporativos',
    subtitle:
      'A exposição dos eventos corporativos é essencial para decretar o seu sucesso. A cobertura fotográfica é, portanto, imprescindível para divulgar a realização de feiras, lançamentos, palestras, inaugurações, confraternizações e uma infinidade de eventos que valorizem a imagem da empresa. O acompanhamento dos eventos permite capturar imagens de interação da empresa com seus clientes, divulgando de forma instantânea e completa todo o seu potencial.',
    image: 'images/covers/corporative_events.jpeg',
  },
  {
    title: 'Indústriais',
    subtitle:
      'A fotografia industrial consegue mostrar uma fábrica em ação, revelando a perfeita sinergia entre profissionais, processo e equipamentos. Dos pequenos detalhes às amplas imagens produtivas, são destacadas as características que movem a empresa, sua infraestrutura, sua tecnologia e a qualificação de seus profissionais.',
    image: 'images/covers/industrial.jpeg',
  },
  {
    title: 'Interiores',
    subtitle:
      'A fotografia registra a beleza dos ambientes através dos traços da arquitetura, da decoração e da iluminação. Para uma composição de qualidade, é necessário enquadramento adequado, bom gosto e técnicas apuradas de captação de cor, textura, perspectiva, detalhes e luz.',
    image: 'images/covers/interiors.jpeg',
  },
  {
    title: 'Produtos',
    subtitle:
      'A técnica da fotografia Still extrai todos os detalhes de produtos, destacando suas formas, texturas e qualidade de acabamento. O profissionalismo envolvido em todo o processo de captura da imagem e pós-produção garante imagens que agregam valor ao produto. A Metzger Fotografia realiza o trabalho em seu próprio estúdio ou na empresa através de equipamentos móveis.',
    image: 'images/covers/products.jpeg',
  },
  {
    title: 'Profissionais',
    subtitle:
      'A fotografia executiva ajuda a dar uma imagem humanizada à empresa. Ela releva o engajamento das pessoas que formam uma empresa, mostra o trabalho integrado de equipes e destaca o atendimento diferenciado que ela pode oferecer ao mercado.',
    image: 'images/covers/professionals.jpeg',
  },
]